# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# see: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
spring:
  application:
    name: trio
  # default active profile HSQLDB (for dev)
  profiles:
    active: hsqldb
  # INTERNATIONALIZATION
  messages:
    basename: messages/messages
  mvc:
    # Path pattern used for static resources.
    static-path-pattern: /resources/**
    throw-exception-if-no-handler-found: true
  # THYMELEAF
  thymeleaf:
    # allows Thymeleaf templates to be reloaded at dev time
    cache: false
  # JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  # DATA REST (RepositoryRestProperties)
  data:
    rest:
      base-path: /api
  jackson:
    serialization:
      write-dates-as-timestamps: false

# ----------------------------------------
# SERVER PROPERTIES
# ----------------------------------------
server:
  port: ${PORT:9090}
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 3600 # 1h
  tomcat:
    basedir: target/tomcat

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------
#security.user.name=user # login username
#security.user.password=changeme
#security.user.role=USER # role assigned to the user
security:
  require-ssl: true
  enable-csrf: true
  basic.enabled: false

# ----------------------------------------
# CUSTOM --- Trio
# ----------------------------------------
trio:
  rememberMe:
    key: trio
    param: rememberMe
  game:
    inactivity_timeout: 600000
