create table authorities (
  id bigint generated by default as identity (start with 1),
  authority varchar(255) not null,
  primary key (id)
)

create table users (
  id bigint generated by default as identity (start with 1),
  enabled boolean,
  fullname varchar(255),
  password varchar(255),
  status integer,
  username varchar(255),
  primary key (id),
  constraint UK_username unique (username)
)

create table user_authorities (
  user_id bigint not null,
  authority_id bigint not null,
  primary key (user_id, authority_id),
  constraint FK_user_authorities_2_authority_id foreign key (authority_id) references authorities,
  constraint FK_user_authorities_2_user_id foreign key (user_id) references users
)

-- ----------------------------------------------------------
-- Authority
-- ----------------------------------------------------------
-- insert into authorities (id, authority) values (1, 'ROLE_ADMIN');
-- insert into authorities (id, authority) values (2, 'ROLE_USER');

-- ----------------------------------------------------------
-- User
-- ----------------------------------------------------------
-- password 'admin'
-- insert into users (id, username, fullname, password, enabled, status) values (1, 'admin', 'Administrator', '$2a$10$jbqsQ21a4nSqgJjmfBblJ.e1PdfWhuj/Um557OY./alTnZoJROQyW', true, 1);

-- ----------------------------------------------------------
-- user_authorities
-- ----------------------------------------------------------
-- insert into user_authorities (user_id, authority_id) values (1, 1);
